
---
services:
  genie-test:
    environment:
      - TERM=xterm
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - GENIE_ADD_COMMAND_HTOP="htop"
      - GENIE_ADD_COMMAND_LL="ls
      - GENIE_APACHE_BIND_PORTS="80:80,443:443"
      - GENIE_APACHE_ENABLED="1"
      - GENIE_APACHE_HTTPS_PORT="443"
      - GENIE_APACHE_HTTP_PORT="80"
      - GENIE_APACHE_NO_LOG_REGEX="\.(gif|jpe?g|png|ico)$$"
      - GENIE_APACHE_PUBLIC_PATH="public_html"
      - GENIE_BROWSER_OPEN_AT_UPPED="1"
      - GENIE_BROWSER_OPEN_IN_PORT="80"
      - GENIE_BROWSER_OPEN_SCHEMA="http"
      - GENIE_DLSYNC_DEFAULT_ARGV=""
      - GENIE_DLSYNC_LFTP_OPTION="--verbose
      - GENIE_DLSYNC_LOCAL_DIR="public_html"
      - GENIE_DLSYNC_REMOTE_DIR="/public_html"
      - GENIE_DLSYNC_REMOTE_HOST=""
      - GENIE_DLSYNC_REMOTE_PASS=""
      - GENIE_DLSYNC_REMOTE_USER=""
      - GENIE_DOCKER_HOSTS="genie-test.com:127.0.0.1"
      - GENIE_DOCKER_IMAGE="kazaoki/genie"
      - GENIE_DOCKER_NAME="genie-test"
      - GENIE_DOCKER_OPTIONS="--cpuset-cpus=0-1"
      - GENIE_DOCKER_OPTIONS_BUILD="--cpuset-cpus=0-1"
      - GENIE_GENERAL_CONFIG_DIR="/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/.genie"
      - GENIE_GENERAL_CONFIG_FILE="/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/.genie/config.pl"
      - GENIE_GENERAL_CONFIG_NAME="config"
      - GENIE_GENERAL_DRIVE_LETTER="c"
      - GENIE_GENERAL_HOME_DIR="/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop"
      - GENIE_GENERAL_HOST_IP="192.168.99.100"
      - GENIE_GENERAL_RUNMODE="product"
      - GENIE_LOGS_FILES="/var/log/httpd/access_log,/var/log/httpd/error_log"
      - GENIE_MYSQL_DATABASES_1_BIND_PORTS="3306"
      - GENIE_MYSQL_DATABASES_1_CHARSET="utf8"
      - GENIE_MYSQL_DATABASES_1_DUMP_GENEL="3"
      - GENIE_MYSQL_DATABASES_1_HOST="db1.kazaoki.jp"
      - GENIE_MYSQL_DATABASES_1_LABEL="db1"
      - GENIE_MYSQL_DATABASES_1_NAME="genie_db1"
      - GENIE_MYSQL_DATABASES_1_PASS="123456789"
      - GENIE_MYSQL_DATABASES_1_REPOSITORY="mysql:5.5"
      - GENIE_MYSQL_DATABASES_1_USER="genie_user1"
      - GENIE_MYSQL_DATABASES_2_BIND_PORTS="3306:3306"
      - GENIE_MYSQL_DATABASES_2_CHARSET="utf8"
      - GENIE_MYSQL_DATABASES_2_DUMP_GENEL="2"
      - GENIE_MYSQL_DATABASES_2_HOST="db-wp.kazaoki.jp"
      - GENIE_MYSQL_DATABASES_2_LABEL="wp"
      - GENIE_MYSQL_DATABASES_2_NAME="wp"
      - GENIE_MYSQL_DATABASES_2_PASS="123456"
      - GENIE_MYSQL_DATABASES_2_REPOSITORY="mysql:5.7"
      - GENIE_MYSQL_DATABASES_2_USER="wp"
      - GENIE_MYSQL_ENABLED="1"
      - GENIE_NGINX_BIND_PORTS="8080:8080"
      - GENIE_NGINX_HTTP_PORT="8080"
      - GENIE_NGINX_PUBLIC_PATH="public_html/test"
      - GENIE_NGROK_ARGS="http
      - GENIE_NGROK_AUTHTOKEN=""
      - GENIE_NGROK_BASIC_PASS=""
      - GENIE_NGROK_BASIC_USER=""
      - GENIE_NGROK_SUBDOMAIN=""
      - GENIE_POSTFIX_FORCE_ENVELOPE="webmaster@kazaoki.jp"
      - GENIE_POSTGRESQL_DATABASES_1_BIND_PORTS="5432:5432"
      - GENIE_POSTGRESQL_DATABASES_1_DATA_VOLUME_LOCK="1"
      - GENIE_POSTGRESQL_DATABASES_1_DUMP_GENEL="3"
      - GENIE_POSTGRESQL_DATABASES_1_HOST="db1.com"
      - GENIE_POSTGRESQL_DATABASES_1_LABEL="db1"
      - GENIE_POSTGRESQL_DATABASES_1_LOCALE="ja_JP.UTF-8"
      - GENIE_POSTGRESQL_DATABASES_1_NAME="genie_db1"
      - GENIE_POSTGRESQL_DATABASES_1_PASS="123456789"
      - GENIE_POSTGRESQL_DATABASES_1_REPOSITORY="postgres:9.4"
      - GENIE_POSTGRESQL_DATABASES_1_USER="genie_user1"
      - GENIE_POSTGRESQL_DATABASES_2_BIND_PORTS="5432"
      - GENIE_POSTGRESQL_DATABASES_2_DUMP_GENEL="1"
      - GENIE_POSTGRESQL_DATABASES_2_LABEL="test-db"
      - GENIE_POSTGRESQL_DATABASES_2_LOCALE="ja_JP.UTF-8"
      - GENIE_POSTGRESQL_DATABASES_2_NAME="genie_db2"
      - GENIE_POSTGRESQL_DATABASES_2_PASS="123456789"
      - GENIE_POSTGRESQL_DATABASES_2_REPOSITORY="postgres:9.3"
      - GENIE_POSTGRESQL_DATABASES_2_USER="genie_user2"
      - GENIE_SPEC_DEFAULT_CAPTURE_WIDTH="1280"
      - GENIE_SPEC_DEFAULT_USER_AGENT=""
      - GENIE_SPEC_JS_ERRORS="0"
    extra_hosts:
      - genie-test.com:127.0.0.1
    image: kazaoki/genie
    links:
      - genie-test-mysql-db1:genie-test-mysql-db1
      - genie-test-mysql-wp:genie-test-mysql-wp
    ports:
      - 80:80
      - 443:443
    volumes:
      - /c/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/.genie/genie:/genie
      - /c/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/public_html:/var/www/html
  genie-test-mysql-db1:
    command:
      - mysqld
    entrypoint:
      - /mysql/opt/before-entrypoint.sh
    environment:
      - MYSQL_LABEL=db1
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=genie_db1
      - MYSQL_USER=genie_user1
      - MYSQL_PASSWORD=123456789
      - MYSQL_CHARSET=utf8
      - TERM=xterm
    extra_hosts:
      - db1.kazaoki.jp:127.0.0.1
    image: mysql:5.5
    ports:
      - '3306'
    volumes:
      - /c/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/.genie/mysql:/mysql
      - genie-test-mysql-db1:/var/lib/mysql
  genie-test-mysql-wp:
    command:
      - mysqld
    entrypoint:
      - /mysql/opt/before-entrypoint.sh
    environment:
      - MYSQL_LABEL=wp
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=wp
      - MYSQL_USER=wp
      - MYSQL_PASSWORD=123456
      - MYSQL_CHARSET=utf8
      - TERM=xterm
    extra_hosts:
      - db-wp.kazaoki.jp:127.0.0.1
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - /c/Users/kazaoki/Documents/LOCAL_Services/kazaoki-genie/work/develop/.genie/mysql:/mysql
      - genie-test-mysql-wp:/var/lib/mysql
version: '2'
volumes:
  genie-test-mysql-db1:
    driver: local
  genie-test-mysql-wp:
    driver: local
