#!perl --

use strict;
use utf8;

# 第一引数により関数にジャンプ
{
	no strict;
	$ARGV[0]->();
}

print "\x1b[31m";
print "\n".('- 'x30)."\n";
print "\x1b[39m";




exit;

# ====================================================================
# genie init                                                    初期化
# ====================================================================
sub init {
	# -- 設定ディレクトリの作成
	if( ! -d '.genie') {
		mkdir '.genie';
		`attrib +h .genie` if $^O=~/MSWIN/; # Windowsなら隠しフォルダにする
	}

print "INIT !";

	# -- 初期設定ファイルの作成
}
